services:
  selenium:
    build: ./
    container_name: Emarge
    shm_size: 2g
    volumes:
      - ./app/:/app/
    environment:
      - FORMATION=X
      - ANNEE=X
      - TP=X
      - Us=USER
      - Pa=PASS
      - TZ=Europe/Paris
    restart: unless-stopped
