services:
  selenium:
    build: ./
    container_name: Emarge
    shm_size: 2g
    volumes:
      - ./app/:/app/
    environment:
      - CourseID=10731
      - AttendanceID=433339
      - Us=USER
      - Pa=PASS
      - St=Présent #Absent #Excusé

